### PR TITLE
Update for Wagtail 2.0

### PR DESCRIPTION
**Pull request by SalahAdDin**

### CODE REVIEW

**Comment by kaedroho** [comment]
Thanks!

If possible, I'd like to keep support for Wagtail 1.x. I think this could be achieved by doing the imports like so:

```
import wagtail.VERSION

if wagtail.VERSION >= (2, 0):
    from wagtail.core import hooks
else:
    from wagtail.wagtailcore import hooks
```

**Comment by SalahAdDin** [comment]
Normally i would say you put a line between support package, but i think this package import a few librarys from `wagtail`, so, it's possible apply this compatibility fix.

Thank you @kaedroho

**Comment by kaedroho** [comment]
Thanks again!

**Comment by ababic** [comment]
Hi @SalahAdDin / @kaedroho - In an effort to add Wagtail 2.0 / Django 2.0 support to wagtailmenus, i'm including the master branch of condensedinlinepanel in my project to run against `wagtail==2.0.0b1` and am experiencing a few issues.

Firstly, `import wagtail.VERSION` raises and `ImportError`. I've had success locally changing this to
`from wagtail import VERSION as WAGTAIL_VERSION` and using `WAGTAIL_VERSION` in conditionals instead.

Secondly, `BaseInlinePanel` seems to have been removed from `wagtail.admin.edit_handlers` in resulting in another `ImportError`.

I've attempted to import and subclass `wagtail.admin.edit_handlers.InlinePanel` instead, but this results in a number of errors when the edit page is actually loaded.

**Pull request merged**
